### ISSUE TITLE
Spark-shp not in Maven

### ISSUE THREAD

**Issue by annadodson787** [mraad/spark-shp#3]
Hi! 

I was hoping to use your library following the steps you provided. Unfortunately, it wasn't finding it -- and looking at Maven repos, seems that the line `spark-shell --packages com.esri:spark-shp:0.8` isn’t working when looking in public repos. 

Is the package deprecated? If not, would it be possible to re-expose it to Maven?

**Comment by mraad** [comment]
Clone this project, mvn install it and voila :-)
